title:             Ocean Nguyen | Official Website
welcome:           Welcome!
email:             duongnd2016@gmail.com
description:       Engineer/Video Creator
author:            Ocean Nguyen
baseurl:           ""
url:               "https://duongnd.com"
port:               3000

# Social Profiles
instagram_username: oceanoppa
twitter_username:
github_username:   oceannguyen
facebook_username: ndaiduong

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
