title:             Ocean Nguyen's Blog
email:             duongnd2016@gmail.com
description:       A Blog written by Ocean Nguyen
author:            Ocean Nguyen
baseurl:           "/oceannguyen.github.io"
url:               "https://duongnd.com"

# Social Profiles
twitter_username:  SBootstrap
github_username:   oceannguyen
facebook_username: ndaiduong

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude: [vendor]
